SN32: Add PAL callback support
ChibiOS/ChibiOS-Contrib pull request #360
Opened 2023-01-29 15:21 UTC by 1Conan

Adds PAL callbacks to SN32F2xx

Tested on SN32F248B

2023-01-31 22:34 UTC, dexter93 submitted a review, later dismissed

2023-04-26 09:02 UTC, dexter93 requested changes
changes to make it build

2023-04-26 09:02 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
>      iopadid_t pad;
```suggestion
```

2023-04-26 09:02 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +            _pal_isr_code(offset + pad)
```suggestion
            _pal_isr_code(offset + pad);
```

2023-04-26 09:02 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
>    _pal_lld_enablepadevent(ioport, pad, PAL_EVENT_MODE_DISABLED);
```suggestion
void _pal_lld_disablepadevent(ioportid_t port, iopadid_t pad) {
  _pal_lld_enablepadevent(port, pad, PAL_EVENT_MODE_DISABLED);
```

2023-04-26 09:19 UTC, dexter93 requested changes
standardize on `port` usage vs `ioport` across the pal stack

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +void _pal_lld_enablepadevent(ioportid_t ioport,
```suggestion
void _pal_lld_enablepadevent(ioportid_t port,
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +      ioport->IE  |= (1 << pad);
```suggestion
      port->IS  &= ~(1 << pad);
      port->IBS &= ~(1 << pad);
      port->IEV &= ~(1 << pad);
      port->IE  |= (1 << pad);
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +      ioport->IE  |= (1 << pad);
```suggestion
      port->IS  &= ~(1 << pad);
      port->IBS &= ~(1 << pad);
      port->IEV |= (1 << pad);
      port->IE  |= (1 << pad);
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +      ioport->IE  |= (1 << pad);
```suggestion
      port->IS  &= ~(1 << pad);
      port->IBS |= (1 << pad);
      port->IE  |= (1 << pad);
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +      ioport->IE  &= ~(1 << pad);
```suggestion
      port->IS  &= ~(1 << pad);
      port->IBS &= ~(1 << pad);
      port->IEV &= ~(1 << pad);
      port->IE  &= ~(1 << pad);
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> + * @param[in] ioport    port containing pad whose event is to be disabled
```suggestion
 * @param[in] port    port containing pad whose event is to be disabled
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +  _pal_lld_enablepadevent(ioport, pad, PAL_EVENT_MODE_DISABLED);
```suggestion
void _pal_lld_disablepadevent(ioportid_t port, iopadid_t pad) {
  _pal_lld_enablepadevent(port, pad, PAL_EVENT_MODE_DISABLED);
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> + * @param[in] ioport   port containing the pad
```suggestion
 * @param[in] port   port containing the pad
```

2023-04-26 09:19 UTC, dexter93 commented on os/hal/ports/SN32/LLD/SN32F2xx/GPIO/hal_pal_lld.c
> +  return ((ioport->IE >> pad) & 1);
```suggestion
bool _pal_lld_ispadeventenabled(ioportid_t port, iopadid_t pad) {
  return ((port->IE >> pad) & 1);
```

2023-07-17 09:36 UTC, fpoussin approved these changes

2023-07-17 09:36 UTC, merged

2023-07-17 09:36 UTC, fpoussin commented
Thank you :)