[WB32 MCU] Update isr.
ChibiOS/ChibiOS-Contrib pull request #406
Opened 2024-06-14 02:07 UTC by itarze

2024-07-22 08:53 UTC, itarze commented
review the PR, please!

2024-08-04 17:26 UTC, fpoussin requested changes

2024-08-04 17:26 UTC, fpoussin commented on demos/WB32/RT-WB32F3G71-RTC/main.c
> +    // chprintf((BaseSequentialStream *)&SERIAL_DEBUG_DRIVER,
Please remove the code if it's not needed anymore.

2024-08-05 01:04 UTC, itarze commented on demos/WB32/RT-WB32F3G71-RTC/main.c
> +    //          RTC_ALARMPERIOD, timespec.year, timespec.month, timespec.dstflag, timespec.dayofweek, timespec.day, timespec.millisecond);
```suggestion
```

2024-08-11 11:33 UTC, fpoussin approved these changes

2024-08-11 11:33 UTC, merged

2024-08-11 11:33 UTC, fpoussin commented
Thanks!